"""users table

Revision ID: ec96d85a5e45
Revises: 7b9cb9fa6247
Create Date: 2019-06-05 15:54:43.557812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec96d85a5e45'
down_revision = '7b9cb9fa6247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_wish_list', table_name='user')
    op.drop_column('user', 'wish_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wish_list', sa.VARCHAR(length=500), nullable=True))
    op.create_index('ix_user_wish_list', 'user', ['wish_list'], unique=1)
    # ### end Alembic commands ###
